# Generated by Django 2.0.2 on 2018-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('product_image_url', models.CharField(max_length=255)),
                ('product_stock', models.CharField(max_length=255)),
                ('product_rating', models.CharField(max_length=255)),
                ('product_url', models.CharField(max_length=255)),
                ('product_subtitle', models.CharField(max_length=255)),
            ],
        ),
    ]
